services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: alxtravel_db
      MYSQL_USER: alxuser
      MYSQL_PASSWORD: alxpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data:
